### PR TITLE
Add Hungarian language

### PR DESCRIPTION
**Pull request by mdhtr**

### CODE REVIEW

**Comment by bennorichters** [comment]
@mdhtr  Would "Csak utcai átvétel" be an option as a translation for "Curbside pickup only"? In your translation it focuses on not having physical contact, but it leaves the possibility open to go inside, which is not what the message is supposed to convey.

**Comment by bennorichters** [comment]
@mdhtr I know it's more common in Hungarian to have exclamation marks at the end of a sentence, but it's not 100% necessary. So, to be consistent with other languages, I would rather leave them out.

**Comment by mdhtr** [comment]
@bennorichters 

> Would "Csak utcai átvétel" be an option as a translation for "Curbside pickup only"? In your translation it focuses on not having physical contact, but it leaves the possibility open to go inside, which is not what the message is supposed to convey.

I'm not really sure how curbside pickup would translate to Hungarian. According to the web, curbside pickup is when you don't even have to get out of your car to pick up something, you just drive by. I'm not sure this service exists in Hungary at all, but correct me if I'm wrong. I focused on contactless pickup because I thought that was the essence of curbside pickup. I approached this translation from a point of view, where Hungarians would like to put up multilingual signs, but I realize that you approached it from the other side, when non-Hungarians would like to put up Hungarian signs, in which case a translation is better than a misleading equivalent. "Csak utcai átvétel" would probably confuse me, but I think we have "kiadóablakos kiadás" and "autós átvétel" that could be used.

About the exclamation mark, I know it seems weird compared to the other languages, but if I remember my language lessons correctly, this is not something that is simply "more common", but rather the language rule on how to do imperative mood and exclamation. (See [Magyar Helyesírás Szabályai 241.d)](https://helyesiras.mta.hu/helyesiras/default/akh12#F9_2)) That said, I'll check if I can come up with equivalent statements that have the same effect.

**Comment by mdhtr** [comment]
@bennorichters I made some adjustments based on commonly used language in signage, and also edited curbside pickup. I think the exclamation marks are grammatically correct so I kept all of them.

**Comment by rspilker** [comment]
In the meantime, the flags have been removed, and the languages.js file now contains the name of the language in their language. This will lead to merge problems.

**Comment by bennorichters** [comment]
OK, I pulled this one

**Pull request merged**
